"""
env/g1_reach_env.py  —  MuJoCo Gymnasium environment for G1 upper-body reaching
================================================================================

Actuator model  (matches unitree_mujoco g1_29dof.xml exactly)
--------------------------------------------------------------
The MJCF uses <motor> actuators — data.ctrl[i] is a direct torque command in
Newton-metres.  The RL policy outputs desired joint positions; a PD controller
implemented here converts those to torques each physics substep:

    τ_i = kp_i * (q_des_i − q_i) − kd_i * qd_i

Torques are clamped to each actuator's ctrlrange before being written to
data.ctrl.  This mirrors the real Unitree G1 SDK LowCmd pipeline (kp, kd, q,
dq per joint) so sim-to-real transfer requires no actuator-model change.

End-effector site
-----------------
"right_hand_ee" is defined directly in g1_29dof.xml inside right_wrist_yaw_link
at pos="0.085 -0.003 0" (palm centre of right_rubber_hand mesh).
No runtime injection; just mj_name2id at init.

Observation  (single step = 45-dim, stacked × 5 → 225-dim network input)
--------------------------------------------------------------------------
  [0 :3 ]  rel_target    = target_pos − ee_pos          (scale × 1.0)
  [3 :17]  joint_pos_rel = q − q_default                (scale × 1.0, noise ±0.01)
  [17:31]  joint_vel     = qd                           (scale × 0.05, noise ±1.5)
  [31:45]  last_action   (no noise)

Action  (14-dim, clipped to [−1, 1])
-------------------------------------
  q_des = q_default + action × action_scale   (action_scale = 0.25 rad)
  → PD controller → torques → data.ctrl

Controlled joints  (14, upper body)
-------------------------------------
  waist ×3, right arm ×7 (shoulder ×3 + elbow + wrist ×3), left arm ×4

Changes from previous version (v3 → v4)
-----------------------------------------
  - Left arm joints (left_shoulder_pitch/roll/yaw + left_elbow) are now locked
    to qpos=0, qvel=0 every physics substep, same mechanism as leg locking.
    The policy still outputs 14 actions (architecture unchanged), but the left
    arm actions have no effect. This stops the left arm from flopping/falling
    under reaction forces.
  - rew_weight_joint_dev should be set to 0.0 in config.py for this version.
    The previous -0.005 penalty was suppressing elbow extension: the policy
    found it cheaper to pivot the shoulder (small deviation) than extend the
    elbow (large deviation required to actually reach targets).

Previous changes (v2 → v3)
---------------------------
  - PD gains halved (waist kp 200→100, shoulder/elbow kp 40→20, wrist kp 10→5)
    to reduce oscillation / vibration seen during visual inspection.
  - Leg joints locked to default every physics substep to prevent passive
    flopping from reaction forces generated by upper-body motion.
"""

import numpy as np
import mujoco
import gymnasium as gym
from gymnasium import spaces
from collections import deque
from typing import Optional, Tuple, Dict

from config import G1Config


# ── Controlled joint names — must match g1_29dof.xml exactly ─────────────────

CONTROLLED_JOINTS = [
    # Waist  (3)
    "waist_yaw_joint",
    "waist_roll_joint",
    "waist_pitch_joint",
    # Right arm  (7)
    "right_shoulder_pitch_joint",
    "right_shoulder_roll_joint",
    "right_shoulder_yaw_joint",
    "right_elbow_joint",
    "right_wrist_roll_joint",
    "right_wrist_pitch_joint",
    "right_wrist_yaw_joint",
    # Left arm  (4) — in action space for architecture continuity, but locked
    "left_shoulder_pitch_joint",
    "left_shoulder_roll_joint",
    "left_shoulder_yaw_joint",
    "left_elbow_joint",
]
N_JOINTS = len(CONTROLLED_JOINTS)   # 14

# ── Leg joint names — locked to default (qpos=0, qvel=0) every step ──────────
# These joints are NOT controlled by the policy; locking them prevents passive
# flopping from reaction forces generated by the upper-body motion.
LEG_JOINTS = [
    "left_hip_pitch_joint",
    "left_hip_roll_joint",
    "left_hip_yaw_joint",
    "left_knee_joint",
    "left_ankle_pitch_joint",
    "left_ankle_roll_joint",
    "right_hip_pitch_joint",
    "right_hip_roll_joint",
    "right_hip_yaw_joint",
    "right_knee_joint",
    "right_ankle_pitch_joint",
    "right_ankle_roll_joint",
]

# ── Left arm joint names — locked to default every step ──────────────────────
# The policy outputs actions for these joints (architecture unchanged, 14-dim)
# but they are overridden to zero every substep.  This prevents the left arm
# from falling/flopping due to reaction forces from right-arm motion.
LEFT_ARM_JOINTS = [
    "left_shoulder_pitch_joint",
    "left_shoulder_roll_joint",
    "left_shoulder_yaw_joint",
    "left_elbow_joint",
]

# ── PD gains — halved from original to reduce oscillation ────────────────────
# Original: waist kp=200, shoulder/elbow kp=40, wrist kp=10
# Halved  : waist kp=100, shoulder/elbow kp=20, wrist kp=5
# kd scaled proportionally (critical damping ratio preserved)

KP = {
    "waist_yaw_joint":              60.0,   # was 100
    "waist_roll_joint":             60.0,   # was 100
    "waist_pitch_joint":            60.0,   # was 100
    "right_shoulder_pitch_joint":   12.0,   # was 20
    "right_shoulder_roll_joint":    12.0,   # was 20
    "right_shoulder_yaw_joint":     12.0,   # was 20
    "right_elbow_joint":            12.0,   # was 20
    "right_wrist_roll_joint":        3.0,   # was 5
    "right_wrist_pitch_joint":       3.0,   # was 5
    "right_wrist_yaw_joint":         3.0,   # was 5
    "left_shoulder_pitch_joint":    12.0,   # was 20
    "left_shoulder_roll_joint":     12.0,   # was 20
    "left_shoulder_yaw_joint":      12.0,   # was 20
    "left_elbow_joint":             12.0,   # was 20
}

KD = {
    "waist_yaw_joint":               2.0,   # was 3
    "waist_roll_joint":              2.0,   # was 3
    "waist_pitch_joint":             2.0,   # was 3
    "right_shoulder_pitch_joint":    0.8,   # was 1.5
    "right_shoulder_roll_joint":     0.8,   # was 1.5
    "right_shoulder_yaw_joint":      0.8,   # was 1.5
    "right_elbow_joint":             0.8,   # was 1.5
    "right_wrist_roll_joint":        0.2,   # was 0.3
    "right_wrist_pitch_joint":       0.2,   # was 0.3
    "right_wrist_yaw_joint":         0.2,   # was 0.3
    "left_shoulder_pitch_joint":     0.8,   # was 1.5
    "left_shoulder_roll_joint":      0.8,   # was 1.5
    "left_shoulder_yaw_joint":       0.8,   # was 1.5
    "left_elbow_joint":              0.8,   # was 1.5
}

# EE site defined in g1_29dof.xml at right_wrist_yaw_link
EE_SITE_NAME     = "right_hand_ee"
# Pelvis nominal standing height from g1_29dof.xml worldbody pos z=0.793
PELVIS_NOMINAL_Z = 0.793


# ─────────────────────────────────────────────────────────────────────────────

class G1ReachEnv(gym.Env):
    """
    Gymnasium environment: Unitree G1 upper-body reaching task.

    The policy controls 14 upper-body joints via a PD torque layer.
    The right hand must reach a randomly sampled 3-D target each episode.
    Leg joints and left arm joints are locked to zero every physics step.
    """

    metadata = {"render_modes": ["human", "rgb_array"], "render_fps": 50}

    def __init__(self, cfg: G1Config = None, render_mode: Optional[str] = None):
        super().__init__()
        self.cfg = cfg or G1Config()
        self.render_mode = render_mode

        # ── Load model ────────────────────────────────────────────────────────
        self.model = mujoco.MjModel.from_xml_path(self.cfg.model_xml)
        self.data  = mujoco.MjData(self.model)
        self.model.opt.timestep = 1.0 / self.cfg.physics_hz

        # ── Controlled joint indices ──────────────────────────────────────────
        self._jnt_ids    = self._resolve_joint_ids()
        self._qpos_addrs = [self.model.jnt_qposadr[j] for j in self._jnt_ids]
        self._qvel_addrs = [self.model.jnt_dofadr[j]  for j in self._jnt_ids]
        self._jnt_ranges = np.array(
            [self.model.jnt_range[j] for j in self._jnt_ids], dtype=np.float64
        )   # shape (N_JOINTS, 2)

        # ── Leg joint indices for locking ─────────────────────────────────────
        self._leg_qpos_addrs, self._leg_qvel_addrs = self._resolve_lock_joint_ids(LEG_JOINTS)

        # ── Left arm joint indices for locking ───────────────────────────────
        self._left_arm_qpos_addrs, self._left_arm_qvel_addrs = self._resolve_lock_joint_ids(LEFT_ARM_JOINTS)

        # ── Actuator indices + torque limits ──────────────────────────────────
        self._act_ids    = self._resolve_actuator_ids()
        self._torque_max = np.array(
            [self.model.actuator_ctrlrange[a, 1] for a in self._act_ids],
            dtype=np.float64
        )

        # ── PD gain arrays ────────────────────────────────────────────────────
        self._kp = np.array([KP[j] for j in CONTROLLED_JOINTS], dtype=np.float64)
        self._kd = np.array([KD[j] for j in CONTROLLED_JOINTS], dtype=np.float64)

        # ── End-effector site ─────────────────────────────────────────────────
        self._ee_site_id = mujoco.mj_name2id(
            self.model, mujoco.mjtObj.mjOBJ_SITE, EE_SITE_NAME
        )
        if self._ee_site_id < 0:
            raise RuntimeError(
                f"Site '{EE_SITE_NAME}' not found. "
                "Add it to right_wrist_yaw_link in g1_29dof.xml."
            )

        # ── Pelvis body ───────────────────────────────────────────────────────
        self._pelvis_id = mujoco.mj_name2id(
            self.model, mujoco.mjtObj.mjOBJ_BODY, "pelvis"
        )

        # ── Target mocap body ─────────────────────────────────────────────────
        self._target_mocap_id = self._get_mocap_id("target_body")

        # ── Default joint positions (neutral = all zeros for G1 upper body) ───
        self._default_qpos = np.zeros(N_JOINTS, dtype=np.float64)

        # ── Domain randomisation state ────────────────────────────────────────
        self._nominal_pelvis_mass: Optional[float] = None
        self._motor_strength = np.ones(N_JOINTS, dtype=np.float64)

        # ── Observation history ───────────────────────────────────────────────
        self._single_obs_dim = self.cfg.obs_dim           # 45
        self._history_len    = self.cfg.history_length    # 5
        self._obs_history: deque = deque(
            [np.zeros(self._single_obs_dim, dtype=np.float32)] * self._history_len,
            maxlen=self._history_len
        )

        # ── Gymnasium spaces ──────────────────────────────────────────────────
        stacked_dim = self._single_obs_dim * self._history_len    # 225
        self.observation_space = spaces.Box(
            low=-np.inf, high=np.inf, shape=(stacked_dim,), dtype=np.float32
        )
        self.action_space = spaces.Box(
            low=-1.0, high=1.0, shape=(N_JOINTS,), dtype=np.float32
        )

        # ── Episode state ─────────────────────────────────────────────────────
        self._step_count     = 0
        self._target_pos     = np.zeros(3, dtype=np.float64)
        self._prev_action    = np.zeros(N_JOINTS, dtype=np.float32)
        self._prev_joint_vel = np.zeros(N_JOINTS, dtype=np.float64)
        self._renderer       = None

    # ─────────────────────────────────────────────────────────────────────────
    # Gymnasium API
    # ─────────────────────────────────────────────────────────────────────────

    def reset(self, *, seed=None, options=None):
        super().reset(seed=seed)

        mujoco.mj_resetData(self.model, self.data)

        # Place pelvis at nominal standing height, zero velocity.
        # Free joint qpos layout: [x, y, z, qw, qx, qy, qz]
        self.data.qpos[0] = 0.0
        self.data.qpos[1] = 0.0
        self.data.qpos[2] = PELVIS_NOMINAL_Z
        self.data.qpos[3] = 1.0   # quaternion w (upright)
        self.data.qpos[4] = 0.0
        self.data.qpos[5] = 0.0
        self.data.qpos[6] = 0.0
        self.data.qvel[:6] = 0.0

        # Lock leg and left arm joints at reset
        self._lock_legs()
        self._lock_left_arm()

        # Domain randomisation
        self._apply_domain_randomisation()

        # Initialise controlled joints near default with ±5 % range noise
        jlo, jhi = self._jnt_ranges[:, 0], self._jnt_ranges[:, 1]
        jspan    = jhi - jlo
        init_q   = self._default_qpos + self.np_random.uniform(
            -0.05, 0.05, size=N_JOINTS
        ) * jspan
        for i, addr in enumerate(self._qpos_addrs):
            self.data.qpos[addr] = float(np.clip(init_q[i], jlo[i], jhi[i]))

        # Small random initial joint velocities (upper body only)
        lo, hi = self.cfg.dr_joint_vel_range
        for addr in self._qvel_addrs:
            self.data.qvel[addr] = float(self.np_random.uniform(lo, hi))

        # Re-lock left arm after the init noise pass (left arm stays at zero)
        self._lock_left_arm()

        # Sample target and move the green sphere
        self._target_pos = self._sample_target()
        if self._target_mocap_id >= 0:
            self.data.mocap_pos[self._target_mocap_id] = self._target_pos

        mujoco.mj_forward(self.model, self.data)

        # Reset episode bookkeeping
        self._step_count     = 0
        self._prev_action    = np.zeros(N_JOINTS, dtype=np.float32)
        self._prev_joint_vel = np.zeros(N_JOINTS, dtype=np.float64)
        self._obs_history    = deque(
            [np.zeros(self._single_obs_dim, dtype=np.float32)] * self._history_len,
            maxlen=self._history_len
        )

        obs  = self._get_stacked_obs()
        info = {"target_pos": self._target_pos.copy()}
        return obs, info

    def step(self, action: np.ndarray):
        action = np.clip(action, -1.0, 1.0).astype(np.float64)

        # ── Decode: normalised action → desired joint positions ───────────────
        q_des = self._default_qpos + action * self.cfg.action_scale
        q_des = np.clip(q_des, self._jnt_ranges[:, 0], self._jnt_ranges[:, 1])

        # Effective kp after motor-strength randomisation
        kp_eff = self._kp * self._motor_strength

        # ── Physics substeps with per-substep PD ─────────────────────────────
        for _ in range(self.cfg.control_decimation):
            q_cur  = self._get_joint_pos()
            qd_cur = self._get_joint_vel()

            # PD law:  τ = kp*(q_des − q) − kd*qd
            torque = kp_eff * (q_des - q_cur) - self._kd * qd_cur
            torque = np.clip(torque, -self._torque_max, self._torque_max)

            # Write only to controlled actuator slots; zero all others
            self.data.ctrl[:] = 0.0
            for i, act_id in enumerate(self._act_ids):
                self.data.ctrl[act_id] = torque[i]

            mujoco.mj_step(self.model, self.data)

            # Lock leg joints every substep — prevent passive flopping
            self._lock_legs()
            # Lock left arm every substep — keeps it neutral, stops falling
            self._lock_left_arm()

        # ── Lock floating base (upper-body task; legs not trained) ───────────
        self.data.qpos[0:3] = [0.0, 0.0, PELVIS_NOMINAL_Z]
        self.data.qpos[3:7] = [1.0, 0.0, 0.0, 0.0]
        self.data.qvel[:6]  = 0.0

        # ── Observation ───────────────────────────────────────────────────────
        single_obs = self._get_single_obs(action.astype(np.float32))
        self._obs_history.append(single_obs)
        stacked_obs = self._get_stacked_obs()

        # ── Reward ────────────────────────────────────────────────────────────
        reward, info = self._compute_reward(action.astype(np.float32))

        # ── Termination ───────────────────────────────────────────────────────
        ee_pos  = self.data.site_xpos[self._ee_site_id].copy()
        dist    = float(np.linalg.norm(ee_pos - self._target_pos))
        success = dist < self.cfg.success_dist
        fall    = self._check_fall()
        terminated = success or fall
        truncated  = self._step_count >= self.cfg.max_episode_steps - 1

        self._step_count    += 1
        self._prev_joint_vel = self._get_joint_vel()
        self._prev_action    = action.astype(np.float32)

        info.update({
            "dist":       dist,
            "success":    success,
            "fall":       fall,
            "ee_pos":     ee_pos,
            "target_pos": self._target_pos.copy(),
        })
        return stacked_obs, reward, terminated, truncated, info

    def render(self):
        if self.render_mode == "rgb_array":
            if self._renderer is None:
                self._renderer = mujoco.Renderer(self.model, height=480, width=640)
            self._renderer.update_scene(self.data)
            return self._renderer.render()

    def close(self):
        if self._renderer is not None:
            self._renderer.close()
            self._renderer = None

    # ─────────────────────────────────────────────────────────────────────────
    # Locking helpers
    # ─────────────────────────────────────────────────────────────────────────

    def _lock_legs(self):
        """
        Pin all leg joints to qpos=0, qvel=0 every substep.
        Prevents passive flopping caused by reaction forces from upper-body motion.
        """
        for addr in self._leg_qpos_addrs:
            self.data.qpos[addr] = 0.0
        for addr in self._leg_qvel_addrs:
            self.data.qvel[addr] = 0.0

    def _lock_left_arm(self):
        """
        Pin left arm joints to qpos=0, qvel=0 every substep.
        The policy still outputs 14 actions (architecture unchanged), but
        left-arm outputs are overridden here so they have no physical effect.
        This stops the left arm falling/flopping under reaction forces.
        """
        for addr in self._left_arm_qpos_addrs:
            self.data.qpos[addr] = 0.0
        for addr in self._left_arm_qvel_addrs:
            self.data.qvel[addr] = 0.0

    # ─────────────────────────────────────────────────────────────────────────
    # Observation
    # ─────────────────────────────────────────────────────────────────────────

    def _get_single_obs(self, last_action: np.ndarray) -> np.ndarray:
        """
        45-dim single-step observation:
          [0:3]    rel_target    = (target − ee) × obs_scale_rel_target
          [3:17]   joint_pos_rel = (q − q_default) × obs_scale_joint_pos + noise
          [17:31]  joint_vel     = qd × obs_scale_joint_vel + noise
          [31:45]  last_action
        """
        ee_pos = self.data.site_xpos[self._ee_site_id].astype(np.float64)

        rel_target = (
            (self._target_pos - ee_pos) * self.cfg.obs_scale_rel_target
        ).astype(np.float32)

        q  = self._get_joint_pos()
        qd = self._get_joint_vel()

        jpos_rel = (
            (q - self._default_qpos) * self.cfg.obs_scale_joint_pos
            + self.np_random.uniform(
                -self.cfg.obs_noise_joint_pos,
                 self.cfg.obs_noise_joint_pos,
                size=N_JOINTS
            )
        ).astype(np.float32)

        jvel = (
            qd * self.cfg.obs_scale_joint_vel
            + self.np_random.uniform(
                -self.cfg.obs_noise_joint_vel,
                 self.cfg.obs_noise_joint_vel,
                size=N_JOINTS
            ) * self.cfg.obs_scale_joint_vel
        ).astype(np.float32)

        return np.concatenate([rel_target, jpos_rel, jvel, last_action]).astype(np.float32)

    def _get_stacked_obs(self) -> np.ndarray:
        return np.concatenate(list(self._obs_history), axis=0).astype(np.float32)

    # ─────────────────────────────────────────────────────────────────────────
    # Reward
    # ─────────────────────────────────────────────────────────────────────────

    def _compute_reward(self, action: np.ndarray) -> Tuple[float, Dict]:
        ee_pos = self.data.site_xpos[self._ee_site_id].copy()
        dist   = float(np.linalg.norm(ee_pos - self._target_pos))
        q      = self._get_joint_pos()
        qd     = self._get_joint_vel()

        r_dist        = self.cfg.rew_weight_dist * dist
        r_success     = self.cfg.rew_weight_success if dist < self.cfg.success_dist else 0.0
        r_alive       = self.cfg.rew_weight_alive
        r_action_rate = self.cfg.rew_weight_action_rate * float(
            np.sum((action - self._prev_action) ** 2)
        )
        r_joint_vel   = self.cfg.rew_weight_joint_vel * float(np.sum(qd ** 2))

        dt   = self.cfg.control_decimation / self.cfg.physics_hz
        jacc = (qd - self._prev_joint_vel) / (dt + 1e-8)
        r_joint_acc = self.cfg.rew_weight_joint_acc * float(np.sum(jacc ** 2))

        ctrl_used = np.array([self.data.ctrl[a] for a in self._act_ids])
        r_energy  = self.cfg.rew_weight_energy * float(np.sum(np.abs(ctrl_used * qd)))

        jlo, jhi  = self._jnt_ranges[:, 0], self._jnt_ranges[:, 1]
        margin    = 0.05 * (jhi - jlo)
        r_dof_lim = self.cfg.rew_weight_dof_limits * float(
            np.sum(
                np.maximum(0.0, jlo + margin - q)
                + np.maximum(0.0, q - (jhi - margin))
            )
        )
        r_joint_dev = self.cfg.rew_weight_joint_dev * float(
            np.sum(np.abs(q - self._default_qpos))
        )

        fall   = self._check_fall()
        r_fall = self.cfg.rew_weight_fall if fall else 0.0

        reward = (
            r_dist + r_success + r_alive + r_action_rate
            + r_joint_vel + r_joint_acc + r_energy
            + r_dof_lim + r_joint_dev + r_fall
        )
        info = {
            "r_dist": r_dist, "r_success": r_success, "r_alive": r_alive,
            "r_action_rate": r_action_rate, "r_joint_vel": r_joint_vel,
            "r_joint_acc": r_joint_acc, "r_energy": r_energy,
            "r_dof_lim": r_dof_lim, "r_joint_dev": r_joint_dev, "r_fall": r_fall,
        }
        return float(reward), info

    # ─────────────────────────────────────────────────────────────────────────
    # Domain Randomisation
    # ─────────────────────────────────────────────────────────────────────────

    def _apply_domain_randomisation(self):
        lo, hi = self.cfg.dr_friction_range
        new_friction = float(self.np_random.uniform(lo, hi))
        for i in range(self.model.ngeom):
            self.model.geom_friction[i, 0] = new_friction

        if self._nominal_pelvis_mass is None:
            self._nominal_pelvis_mass = float(self.model.body_mass[self._pelvis_id])
        lo, hi = self.cfg.dr_mass_range
        self.model.body_mass[self._pelvis_id] = (
            self._nominal_pelvis_mass + float(self.np_random.uniform(lo, hi))
        )

        lo, hi = self.cfg.dr_motor_strength_range
        self._motor_strength = self.np_random.uniform(
            lo, hi, size=N_JOINTS
        ).astype(np.float64)

    # ─────────────────────────────────────────────────────────────────────────
    # Helpers
    # ─────────────────────────────────────────────────────────────────────────

    def _get_joint_pos(self) -> np.ndarray:
        return np.array(
            [self.data.qpos[addr] for addr in self._qpos_addrs], dtype=np.float64
        )

    def _get_joint_vel(self) -> np.ndarray:
        return np.array(
            [self.data.qvel[addr] for addr in self._qvel_addrs], dtype=np.float64
        )

    def _check_fall(self) -> bool:
        return float(self.data.xpos[self._pelvis_id][2]) < self.cfg.fall_height_threshold

    def _sample_target(self) -> np.ndarray:
        """
        Sample uniformly inside a sphere centred at cfg.target_center.
        Center (0.45, -0.15, 1.05) is biased toward the right arm's
        natural reachable zone in front of the torso.
        """
        cx, cy, cz = self.cfg.target_center
        r = self.cfg.target_radius
        while True:
            p = self.np_random.uniform(-1.0, 1.0, size=3) * r
            if np.linalg.norm(p) <= r:
                t = np.array([cx + p[0], cy + p[1], cz + p[2]], dtype=np.float64)
                t[2] = max(t[2], 0.3)   # floor clearance
                return t

    def _resolve_joint_ids(self):
        ids = []
        for name in CONTROLLED_JOINTS:
            jid = mujoco.mj_name2id(self.model, mujoco.mjtObj.mjOBJ_JOINT, name)
            if jid < 0:
                raise ValueError(f"Joint '{name}' not found in model.")
            ids.append(jid)
        return ids

    def _resolve_lock_joint_ids(self, joint_names):
        """
        Resolve qpos/qvel addresses for a list of joint names to lock.
        Joints not present in the MJCF are silently skipped — robust across
        MJCF versions with different joint names.
        Returns (qpos_addrs, qvel_addrs).
        """
        qpos_addrs, qvel_addrs = [], []
        for name in joint_names:
            jid = mujoco.mj_name2id(self.model, mujoco.mjtObj.mjOBJ_JOINT, name)
            if jid >= 0:
                qpos_addrs.append(self.model.jnt_qposadr[jid])
                qvel_addrs.append(self.model.jnt_dofadr[jid])
        return qpos_addrs, qvel_addrs

    def _resolve_actuator_ids(self):
        """
        Find the data.ctrl index for each controlled joint.
        g1_29dof.xml has one <motor> per joint; we match by actuator_trnid.
        """
        jnt_to_act = {
            int(self.model.actuator_trnid[a, 0]): a
            for a in range(self.model.nu)
        }
        act_ids = []
        for jnt_id in self._jnt_ids:
            if jnt_id not in jnt_to_act:
                name = mujoco.mj_id2name(
                    self.model, mujoco.mjtObj.mjOBJ_JOINT, jnt_id
                )
                raise ValueError(f"No actuator found for joint '{name}'.")
            act_ids.append(jnt_to_act[jnt_id])
        return act_ids

    def _get_mocap_id(self, body_name: str) -> int:
        bid = mujoco.mj_name2id(self.model, mujoco.mjtObj.mjOBJ_BODY, body_name)
        if bid < 0:
            return -1
        return int(self.model.body_mocapid[bid])